#!/bin/bash
SCRIPT="$(readlink -f "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"
INVOKED="${0}"

set -eou pipefail

. /.functions

usage()
{
	echo "usage: ${INVOKED} java-exe fs-dir [jvm-args]" 1>&2
	exit 1
}

[ ${#} -lt 2 ] && usage

ARGS=("${@}")
set --
. /configure || fail "Failed to configure properly"
set -- "${ARGS[@]}"

JAVA_EXE="${1}"
[ -n "${JAVA_EXE}" ] || fail "Must provide a non-empty java-exe parameter"
require_exe "${JAVA_EXE}"

FS_DIR="${2}"
[ -n "${FS_DIR}" ] || fail "Must provide a non-empty fs-dir parameter"
require_dir_readwrite "${FS_DIR}"

[ -v AGENT_JAR ] || fail "The environment variable AGENT_JAR must be defined"

shift 2
JVM_ARGS=( "${@}" )

say "FS Dir   = [${FS_DIR}]"
say "Java EXE = [${JAVA_EXE}]"
${JAVA_EXE} -version
say "JVM Args = [${JVM_ARGS[@]}]"

# Now, download the Agent JAR ...

# First, make sure we have the URL
[ -v JENKINS_URL ] || JENKINS_URL=""
if [ -z "${JENKINS_URL}" ] ; then
	URL_FILE="${BASEDIR}/jenkins.url"
	say "No Jenkins URL was defined in the environment, trying to fetch it from [${URL_FILE}]..."
	[ -e "${URL_FILE}" ] || fail "No URL file found"
	[ -f "${URL_FILE}" ] || fail "The path [${URL_FILE}] is not a regular file"
	[ -r "${URL_FILE}" ] || fail "The file [${URL_FILE}] is not readable"
	JENKINS_URL="$(sed -e '/^\s*#/d' -e '/^\s*$/d' < "${URL_FILE}" | head -1 | tr -d '\n')"
	[ -n "${JENKINS_URL}" ] || fail "The URL file did not contain any valid Jenkins URL"
fi

download-agent "${JENKINS_URL}" "${AGENT_JAR}" || exit ${?}

CMD=(
	"${JAVA_EXE}"
	"${JVM_ARGS[@]}"
	-jar "${AGENT_JAR}"
	-noReconnect
	-noKeepAlive
	-agentLog "${FS_DIR}/agent.log"
)
say "🚀 Launching the Java agent as: ${CMD[@]@Q}"
exec "${CMD[@]}"
