#!/bin/bash
set -eou pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

ok()
{
	say "✅ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit 1
}

#
# If we got no arguments, then we need to see if we're on K8s and need
# to launch the agent to reach back into Jenkins ...
#
[ ${#} -eq 0 ] && is-k8s && exec launch-agent-k8s

#
# Final fallback - if there are no arguments, run bsh
#
if [ ${#} -eq 0 ] ; then
	echo -e "Running in interactive mode since no command was given to execute"
	set -- /usr/bin/bash -i
fi

echo -e "Executing the command: ${@@Q}"
exec /configure "${@}"
