#!/bin/bash

if [ ${#} -lt 1 ] ; then
	echo -e "Running in infinity mode since no command was given to execute"
	ARGS=(/usr/bin/sleep infinity)
else
	ARGS=("${@}")
fi

echo -e "Executing the command [${ARGS[@]}]"
exec /configure "${ARGS[@]}"
