apiVersion: "v1"
kind: "Pod"
metadata:
  name: "test-build-worker"
  namespace: "jenkins"
spec:
  containers:
    - name: "jnlp"
      image: "harbor.armedia.net/arkcase-marketplace-cache/arkcase/jenkins-build:3.3.11"
      imagePullPolicy: "Always"
      command: [ "sleep", "infinity" ]
      workingDir: "/home/jenkins"
      env:
        - name: "JAVA"
          value: "11"
        - name: "NODE"
          value: "16.14"
      resources:
        limits:
          memory: "8Gi"
          ephemeral-storage: "16Gi"
        requests:
          memory: "8Gi"
      volumeMounts:
        - mountPath: "/etc/ssl/certs/ca-certificates.crt"
          name: "volume-1"
          readOnly: false
          subPath: "ca-trusts.pem"
        - mountPath: "/etc/ssl/certs/java/cacerts"
          name: "volume-0"
          readOnly: false
          subPath: "cacerts"
        - mountPath: "/cache"
          name: "volume-2"
          readOnly: false
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
  restartPolicy: "Never"
  serviceAccountName: "jenkins-worker"
  volumes:
    - name: "workspace-volume"
      emptyDir: {}
    - name: "volume-0"
      configMap:
        name: "ca-trusts"
        optional: false
    - name: "volume-1"
      configMap:
        name: "ca-trusts"
        optional: false
    - name: "volume-2"
      emptyDir: {}
