#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	say "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [pom.xml-or-directory]" 1>&2
	exit 1
}

[ ${#} -le 1 ] || usage

DIR="."
POM="pom.xml"
if [ ${#} -eq 1 ] ; then
	F="${1}"
	[ -e "${F}" ] || fail "The path [${F}] does not exist"
	if [ -d "${F}" ] ; then
		# If it's a directory, then we use the default POM filename
		DIR="${F}"
	else
		# If it's a file, then split it ...
		DIR="$(dirname "${F}")"
		POM="$(basename "${F}")"
	fi
fi

require_dir_readable "${DIR}"

# Ok ... so the directory is fine, let's use the POM file
cd "${DIR}" || fail "Failed to CD into [${DIR}]"

require_file_readable "${POM}"

# Have to use this, or things may not work properly everywhere
# if an old version of the plugin is used
HELP="org.apache.maven.plugins:maven-help-plugin:3.4.0"

exec mvn "${HELP}:evaluate" -Dexpression=project.version -q -DforceStdout -f "$(basename "${POM}")"
