#!/bin/bash
SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
SCRIPT="$(/usr/bin/basename "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

is_valid_name()
{
	local STR="${1}"
	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
	return 0
}

usage()
{
	echo -e "usage: ${BASH_SOURCE:-${0}} [namespace] secret-name" 1>&2
	exit 1
}

KUBECTL="$(type -P kubectl 2>/dev/null)" || fail "The 'kubectl' executable is not in the path - cannot continue"

[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage

if [ ${#} -eq 1 ] ; then
	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
else
	NAMESPACE="${1}"
	shift
fi
is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"

SECRET_NAME="${1}"
is_valid_name "${SECRET_NAME}" || fail "The secret name [${SECRET_NAME}] is invalid"

[ -v DOCKER_CONFIG ] || DOCKER_CONFIG=""
[ -n "${DOCKER_CONFIG}" ] || DOCKER_CONFIG="${HOME}/.docker"

say "👉 Docker configuration expected at [${DOCKER_CONFIG}]"
DOCKER_CONFIG="$(/usr/bin/readlink -f "${DOCKER_CONFIG}")" || fail "Failed to canonicalize the docker configuration path"
DOCKER_CONFIG+="/config.json"
[ -f "${DOCKER_CONFIG}" ] || fail "No docker login configuration available at [${DOCKER_CONFIG}] - cannot continue!"

say "👉 Creating the Kubernetes secret ${SECRET_NAME} in namespace ${NAMESPACE}"
"${KUBECTL}" get node &>/dev/null || fail "No access to the K8s cluster, cannot continue"

# Ensure the namespace exists
"${KUBECTL}" get namespace "${NAMESPACE}" &>/dev/null || \
	"${KUBECTL}" create namespace "${NAMESPACE}" || \
	fail "Failed to create the required namespace [${NAMESPACE}]"

say "👉 Creating Kubernetes secret (${SECRET_NAME}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."

# Delete the existing secret, if necessary
"${KUBECTL}" delete secret \
	--namespace "${NAMESPACE}" \
	"${SECRET_NAME}" &>/dev/null || true

# Create the replacement secret
"${KUBECTL}" create secret \
	generic \
	--namespace "${NAMESPACE}" \
	"${SECRET_NAME}" \
	--from-file=".dockerconfigjson=${DOCKER_CONFIG}" \
	--type="kubernetes.io/dockerconfigjson" || fail "ERROR: Failed to create the secret ${SECRET_NAME} in namespace ${NAMESPACE} (rc = ${?})"

say "✅ Secret created!"
exit 0
