#!/bin/bash
set -euo pipefail
. /.functions

usage()
{
	echo "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} jenkins-url [target-file]" 1>&2
	exit 1
}

[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage

JENKINS_URL="${1}"
[[ "${JENKINS_URL}" =~ ^https://([a-z0-9.-]+)(:[1-9][0-9]*)?(/.*)?$ ]] || fail "Invalid Jenkins URL [${JENKINS_URL}]"

AGENT_JAR="agent.jar"
[ ${#} -gt 1 ] && AGENT_JAR="${2}"

# Fetch the agent from ${JENKINS_URL}/jnlpJars/agent.jar
AGENT_PATH="/jnlpJars/agent.jar"
[[ "${JENKINS_URL}" =~ /$ ]] && AGENT_PATH="${AGENT_PATH:1}"
SRC_URL="${JENKINS_URL}${AGENT_PATH}"

say "📁 Downloading the agent from [${SRC_URL}] into [${AGENT_JAR}]..."
/usr/bin/curl -fsSL -o "${AGENT_JAR}" "${SRC_URL}" || fail "Failed to download the agent"
ok "Agent downloaded!"
