#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail

[ -v DOWNSCALE_TIMEOUT ] || DOWNSCALE_TIMEOUT=""
[ -n "${DOWNSCALE_TIMEOUT}" ] || DOWNSCALE_TIMEOUT="20m"

[ -v DISABLE_DOWNSCALE ] || DISABLE_DOWNSCALE=""
case "${DISABLE_DOWNSCALE,,}" in
	true | t | yes | y ) DISABLE_DOWNSCALE="true" ;;
	* ) DISABLE_DOWNSCALE="false" ;;
esac
export DISABLE_DOWNSCALE

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

doing()
{
	say "👉 ${@}"
}

ok()
{
	say "✅ ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

is_deployed()
{
	local NAMESPACE="${1}"
	local RELEASE="${2}"
	execute helm get --namespace "${NAMESPACE}" all "${RELEASE}" &>/dev/null
	return ${?}
}

is_valid_name()
{
	local STR="${1}"
	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
	return 0
}

execute()
{
	#
	# Show the command about to be executed
	#
	say "${@@Q}"
	if "${DISABLE_DOWNSCALE}" ; then
		warn "Downscaling disabled: skipping the command execution"
		return 0
	fi

	#
	# Proceed with the execution
	#
	( exec "${@}" )
	return ${?}
}

#
# This function returns the number that serves as
# a multiplier/divisor for a given time scale
#
get_time_mul()
{
	local TAG="${1^^}"

	[[ "${TAG}" =~ ^[HDMS]$ ]] || return 1
	local DURATION_S=1
	local DURATION_M=$(( DURATION_S * 60 ))
	local DURATION_H=$(( DURATION_M * 60 ))
	local DURATION_D=$(( DURATION_H * 24 ))

	local VAR="DURATION_${TAG}"
	echo -n "${!VAR}"
}

#
# This function converts numbers of seconds into
# K8s timespecs, but leaves timespec strings alone
#
secs_to_timestr()
{
	local STR="${1}"
	local NUM="(0|[1-9][0-9]*)"

	[ -n "${STR}" ] || return 1

	# If it's already a time string, return it
	if [[ "${STR^^}" =~ ^(${NUM}D)?(${NUM}H)?(${NUM}M)?(${NUM}S)?$ ]] ; then
		echo -n "${STR,,}"
		return 0
	fi

	[[ "${STR}" =~ ^${NUM}$ ]] || return 1

	local RET=""
	local SIZE=0
	local MUL=0
	local SECS=${STR}
	for C in D H M S ; do
		MUL=$(get_time_mul "${C}")
		(( SIZE = ( SECS / MUL ) ))
		[ ${SIZE} -gt 0 ] && RET+="${SIZE}${C}"
		(( SECS -= ( SIZE * MUL ) ))
	done

	echo -n ${RET,,}
	return 0
}

#
# This function converts K8s timespecs into
# numbers of seconds, but leaves numbers alone
#
timestr_to_secs()
{
	local STR="${1}"
	local NUM="(0|[1-9][0-9]*)"

	# If it's a straight-up number,
	# seconds already, so just return it
	if [[ "${STR}" =~ ^${NUM}$ ]] ; then
		echo -e "${STR}"
		return 0
	fi

	# It could be a time string, so parse it out
	[ -n "${STR}" ] || return 1
	[[ "${STR^^}" =~ ^(${NUM}D)?(${NUM}H)?(${NUM}M)?(${NUM}S)?$ ]] || return 1

	local PARTS=( "${BASH_REMATCH[@]:1}" )
	[ ${#PARTS[@]} -ge 1 ] || return 1

	local SIZE=0
	local MUL=0
	local SECS=0
	for (( i = 0 ; i < ${#PARTS[@]} ; i++ )) ; do
		[[ "${PARTS[i]}" =~ ^${NUM}([DHMS])$ ]] || continue
		SIZE=${BASH_REMATCH[1]}
		MUL=$(get_time_mul "${BASH_REMATCH[2]}")
		(( SECS += SIZE * MUL ))
	done

	echo -n ${SECS}
	return 0
}

list_scalable_items()
{
	local NAMESPACE="${1}"
	local RELEASE="${2}"
	local SELECTOR="${3}"

	local TYPES=(statefulset deployment daemonset)

	for TYPE in "${TYPES[@]}" ; do
		kubectl \
			get "${TYPE}" \
			--namespace "${NAMESPACE}" \
			--selector "${SELECTOR}" \
			--output name
	done | sort -u
}

usage()
{
	echo -e "usage: ${BASH_SOURCE:-${0}} [namespace] release" 1>&2
	exit 1
}

[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage

DOWNSCALE_TIMEOUT=$(timestr_to_secs "${DOWNSCALE_TIMEOUT}") || fail "Invalid value for DOWNSCALE_TIMEOUT: [${DOWNSCALE_TIMEOUT}]"

if [ ${#} -eq 1 ] ; then
	NAMESPACE="$(kubectl config view --minify --output jsonpath="{..namespace}")"
	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
else
	NAMESPACE="${1}"
	shift
fi
is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"

RELEASE="${1}"
is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"

# If there's no deployment, do nothing...
is_deployed "${NAMESPACE}" "${RELEASE}" || fail "The release [${RELEASE}] is not deployed into namespace [${NAMESPACE}] ... can't validate it"

SELECTOR="app.kubernetes.io/instance=${RELEASE},arkcase.com/task=work"

# Delete any prior test pods
# NOTE: the timeout is PER ITEM, not total...
readarray -t ELEMENTS < <(list_scalable_items "${NAMESPACE}" "${RELEASE}" "${SELECTOR}")
if [ ${#ELEMENTS[@]} -le 0 ] ; then
	say "👀 There are no scalable resources to downscale"
	exit 0
fi

doing "Downscaling the ${#ELEMENTS[@]} existing scalable resources..."
execute kubectl scale "${ELEMENTS[@]}" --namespace "${NAMESPACE}" --replicas 0 || fail "Failed to downscale the scalable resources!"

ok "Downscale requested!"
DOWNSCALE_TIMEOUT_STR="$(secs_to_timestr "${DOWNSCALE_TIMEOUT}")"
START="$(date +%s)"
# Wait for all workload pods to disappear...
while true ; do
	say "⌛ Waiting for the downscale to complete (up to ${DOWNSCALE_TIMEOUT_STR} total)..."

	# If this wait succeeds, we need not wait any further ...
	execute kubectl --namespace "${NAMESPACE}" wait --for=delete pods --selector "${SELECTOR}" --timeout "${DOWNSCALE_TIMEOUT_STR}" && break

	# The wait has timed out
	warn "Failed to wait for the workload pods to disappear"

	# Have we timed out yet? If we have, we puke out directly
	NOW="$(date +%s)"
	(( DIFF = ( NOW - START ) )) || true

	# Make sure our wait doesn't put us overbudget on the total wait
	# time period, and make sure that if we have to wait one last time,
	# that it also doesn't exceed our expected timeout
	(( REMAINING = DOWNSCALE_TIMEOUT - DIFF )) || true

	# If there's no remaining time, we puke out ...
	[ ${REMAINING} -gt 0 ] || fail "Timed out waiting for the workload pods to disappear"

	# There's still time remaining, but less than before, so
	# let's use that instead of the original value...
	DOWNSCALE_TIMEOUT=${REMAINING}
	DOWNSCALE_TIMEOUT_STR="$(secs_to_timestr "${DOWNSCALE_TIMEOUT}")"
done
ok "Downscale complete!"
