#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	say "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [pom.xml]" 1>&2
	exit 1
}

[ ${#} -le 1 ] || usage

POM="pom.xml"
if [ ${#} -eq 1 ] ; then
	POM="${1}"
	[ -n "${1}" ] || fail "The POM file path may not be the empty string"
fi

require_file_readable "${POM}"

CHANGELIST="$(mvn -f "${POM}" help:evaluate -Dexpression=changelist -q -DforceStdout 2>&1)" || fail "Failed to compute the changelist using Maven's help:evaluate command: ${CHANGELIST}"

exec tr -d '\n' <<< "${CHANGELIST}"
