#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

usage()
{
	echo -e "usage: ${BASH_ARGV0} git-url"
	exit 1
}

[ ${#} -ne 1 ] && usage

git ls-remote --exit-code --symref "${1}" HEAD | awk -F'[/\t]' 'NR == 1 { print $3 }'
