#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

FUNCTIONS="${BASEDIR}/.functions"
if ! . "${FUNCTIONS}" ; then
	echo -e "ERROR: Failed to load the base functions from [${FUNCTIONS}]"
	exit 1
fi
unset FUNCTIONS

usage()
{
	echo -e "usage: ${BASH_ARGV0} git-url"
	exit 1
}

[ ${#} -ne 1 ] && usage

git ls-remote --exit-code --symref "${1}" HEAD | awk -F'[/\t]' 'NR == 1 { print $3 }'
