#!/bin/bash

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

fail()
{
	say "❌ ${@}"
	exit ${EXIT_CODE:-1}
}

usage()
{
	say "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [pom.xml]" 1>&2
	exit 1
}

[ ${#} -le 1 ] || usage

POM="pom.xml"
if [ ${#} -eq 1 ] ; then
	POM="${1}"
	[ -n "${1}" ] || fail "The POM file path may not be the empty string"
fi

[ -e "${POM}" ] || fail "The POM file [${POM}] does not exist"
[ -f "${POM}" ] || fail "The path [${POM}] is not a regular file"
[ -r "${POM}" ] || fail "The POM file [${POM}] is not readable"

VERSION="$(xmlstarlet sel -N "p=http://maven.apache.org/POM/4.0.0" -t -m "/p:project/*" --if 'name()="version"' -v '.' --else -n --break < "${POM}")" || fail "Failed to parse the /project/version node from the POM file [${POM}]"

exec tr -d '\n' <<< "${VERSION}"
