#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ repository ] workflow runid"
	exit 1
}

[ ${#} -ge 2 ] || usage
[ ${#} -le 3 ] || usage

ARGS="$(getopt -o "h?" -l "help" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage

eval set -- "${ARGS}"

while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;

		* ) usage ;;
	esac
done

REPO=()
if [ ${#} -eq 3 ] ; then
	[ -n "${1}" ] || fail "The repository name may not be an empty string"
	REPO=("${1}")
	shift
fi

WORKFLOW="${1}"
[ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
RUN_ID="${2}"
[ -n "${RUN_ID}" ] || fail "The runId may not be an empty string"

STATUS="$(jq -r ".status" < <(gh-workflow-run-status "${REPO[@]}" "${WORKFLOW}" "${RUN_ID}"))"
FINISHED="false"
[ "${STATUS,,}" == "completed" ] && FINISHED="true"
echo "${FINISHED}"
exit 0
