#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	[ ${#} -eq 0 ] || echo -e "❌ ${@}\n"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} repository workflow [ branch ] [ param1=value1 param2=value2 ... paramN=valueN ]"
	echo -e ""
	echo -e "\tYou can use '.' as teh repository name to identify the GitHub repository from the current directory's checkout"
	exit 1
}

ARGS="$(getopt -o "h?" -l "help" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage

eval set -- "${ARGS}"

while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;

		* ) usage ;;
	esac
done

[ ${#} -ge 2 ] || usage "You must at least specify the repository and the workflow"

REPO="${1}"
[ -n "${REPO}" ] || fail "The repository may not be an empty string"
if [ "${REPO}" == "." ] ; then
	REPO=()
	REPO_PARAM=()
else
	REPO_PARAM=(--repo "${REPO}")
	REPO=("${REPO}")
fi
shift

WORKFLOW="${1}"
[ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
shift

BRANCH=()
if [ ${#} -ge 1 ] ; then
	# This parameter is either the branch name (no = sign) or
	# the first parameter spec
	if [[ ! "${1}" =~ ^[0-9a-zA-Z_]+=.*$ ]] ; then
		BRANCH=(--ref "${1}")
		[ -n "${BRANCH}" ] || fail "The branch name may not be an empty string"
		shift
	fi
fi

#
# Parse out the parameter values to be sent for the build
#
PARAMS=()
for p in "${@}" ; do
	[ -z "${p}" ] && continue
	[[ "${p}" =~ ^[0-9a-zA-Z_]+=.*$ ]] || { warn "The parameter specification [${p}] is not valid - must be in the form name=value" ; continue ; }
	PARAMS+=(-f "${p}")
done

GH_USER_FLAGS=()
[ -v GH_WORKFLOW_USER ] && [ "${GH_WORKFLOW_USER:-""}" ] && GH_USER_FLAGS=(--user "${GH_WORKFLOW_USER}")

LAUNCH_RESULT="$(gh-workflow-run "${REPO_PARAM[@]}" "${BRANCH[@]}" "${WORKFLOW}" "${PARAMS[@]}")" || exit ${?}

LAUNCH_RESULT="$(echo -n "${LAUNCH_RESULT}" | yaml2json)" || fail "Failed to convert the gh-workflow-run output to JSON"

RUN_URL="$(jq -r '.runUrl // ""' <<< "${LAUNCH_RESULT}")"
[ -n "${RUN_URL}" ] && eyes "The GigHub run can be tracked here: ${RUN_URL}"

RUN_ID="$(jq -r '.runId // ""' <<< "${LAUNCH_RESULT}")"
[ -n "${RUN_ID}" ] || fail "Failed to get the run ID for the launched job"

set_or_default RETRY_DELAY "15s"

ATTEMPT=0
while true ; do
	(( ++ATTEMPT ))
	if [ ${ATTEMPT} -gt 1 ] ; then
		sleep "${RETRY_DELAY}" || fail "Interrupted while waiting to try attempt # ${ATTEMPT}"
	fi

	RUN_STATUS="$(gh-workflow-run-status "${REPO[@]}" "${WORKFLOW}" "${RUN_ID}")" || continue

	jq -r <<< "${RUN_STATUS}" &>/dev/null || continue

	STATUS="$(jq -r '.status // "unknown"' <<< "${RUN_STATUS}")" || fail "Failed to parse the run status string: [${RUN_STATUS}]"
	[ "${STATUS,,}" == "completed" ] || continue

	CONCLUSION="$(jq -r '.conclusion // "unknown"' <<< "${RUN_STATUS}")"
	case "${CONCLUSION,,}" in
		neutral | skipped | success ) break ;;
	esac

	RC=0
	gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --exit-status &>/dev/null || RC="${?}"
	[ ${RC} -eq 0 ] && break

	# Always show the full log
	fail "The workflow has completed with an unsuccessful status (rc=${RC}): [${CONCLUSION}]"
	gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --log
done
quit "The workflow has completed successfully!"
