#!/bin/bash
set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} workflow runid"
	exit 1
}

[ ${#} -eq 2 ] || usage


WORKFLOW="${1}"
[ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
RUN_ID="${2}"
[ -n "${RUN_ID}" ] || fail "The runId may not be an empty string"

STATUS="$(jq -r ".status" < <(gh-workflow-run-status "${WORKFLOW}" "${RUN_ID}"))"
FINISHED="false"
[ "${STATUS,,}" == "completed" ] && FINISHED="true"
echo "${FINISHED}"
exit 0
