#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	[ ${#} -eq 0 ] || echo -e "❌ ${@}\n"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} repository workflow [ branch ] [ param1=value1 param2=value2 ... paramN=valueN ]"
	echo -e ""
	echo -e "\tYou can use '.' as teh repository name to identify the GitHub repository from the current directory's checkout"
	exit 1
}

ARGS="$(getopt -o "h?" -l "help" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage

eval set -- "${ARGS}"

while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;

		* ) usage ;;
	esac
done

[ ${#} -ge 2 ] || usage "You must at least specify the repository and the workflow"

REPO="${1}"
[ -n "${REPO}" ] || fail "The repository may not be an empty string"
if [ "${REPO}" == "." ] ; then
	REPO=()
	REPO_PARAM=()
else
	REPO_PARAM=(--repo "${REPO}")
	REPO=("${REPO}")
fi
shift

WORKFLOW="${1}"
[ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
shift

BRANCH=()
if [ ${#} -ge 1 ] ; then
	# This parameter is either the branch name (no = sign) or
	# the first parameter spec
	if [[ ! "${1}" =~ ^[0-9a-zA-Z_]+=.*$ ]] ; then
		BRANCH=(--ref "${1}")
		[ -n "${BRANCH}" ] || fail "The branch name may not be an empty string"
		shift
	fi
fi

#
# Parse out the parameter values to be sent for the build
#
PARAMS=()
for p in "${@}" ; do
	[ -z "${p}" ] && continue
	[[ "${p}" =~ ^[0-9a-zA-Z_]+=.*$ ]] || { warn "The parameter specification [${p}] is not valid - must be in the form name=value" ; continue ; }
	PARAMS+=(-f "${p}")
done

GH_USER_FLAGS=()
[ -v GH_WORKFLOW_USER ] && [ "${GH_WORKFLOW_USER:-""}" ] && GH_USER_FLAGS=(--user "${GH_WORKFLOW_USER}")

LAUNCH_DETAILS="$(gh-workflow-run "${REPO_PARAM[@]}" "${BRANCH[@]}" "${WORKFLOW}" "${PARAMS[@]}")" || exit ${?}

LAUNCH_DETAILS="$(echo -n "${LAUNCH_DETAILS}" | yaml2json)" || fail "Failed to convert the gh-workflow-run output to JSON"

RUN_URL="$(jq -r '.runUrl // ""' <<< "${LAUNCH_DETAILS}")"
[ -n "${RUN_URL}" ] && eyes "The GigHub run can be tracked here: ${RUN_URL}"

RUN_ID="$(jq -r '.runId // ""' <<< "${LAUNCH_DETAILS}")"
[ -n "${RUN_ID}" ] || fail "Failed to get the run ID for the launched job"

set_or_default RETRY_DELAY "15s"

#
# Start the polling cycle
#
ATTEMPT=0
RUN_STATUS=""
STATUS="unknown"
while [ "${STATUS,,}" != "completed" ] ; do
	(( ++ATTEMPT ))
	if [ ${ATTEMPT} -gt 1 ] ; then
		sleep "${RETRY_DELAY}" || fail "Interrupted while waiting to try attempt # ${ATTEMPT}"
	fi

	# What's the run's status?
	RC=0
	RUN_STATUS="$(gh-workflow-run-status "${REPO[@]}" "${WORKFLOW}" "${RUN_ID}")" || RC=${?}
	if [ ${RC} -ne 0 ] ; then
		err "Failed to fetch the run status (rc=${RC}): [${RUN_STATUS}]"
		continue
	fi

	# Is this valid JSON?
	if ! jq -r <<< "${RUN_STATUS}" &>/dev/null ; then
		err "Failed to parse the run status JSON from the string [${RUN_STATUS}]"
		continue
	fi

	# The JSON is OK! Check to see if we must continue polling...
	STATUS="$(jq -r '.status // "unknown"' <<< "${RUN_STATUS}")"
done

#
# The run status says the run has completed, so let's check to see
# what the outcome was, and how we should react to it
#
OUTCOME="$(jq -r '.conclusion // "unknown"' <<< "${RUN_STATUS}")"
RC=0
case "${OUTCOME,,}" in
	neutral | skipped | success ) ;;

	* )	# We don't know the exact status, so we check it directly
		RC=0
		gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --exit-status &>/dev/null || RC="${?}"
		if [ ${RC} -ne 0 ] ; then
			# The exit status shows a failure, so show the full log
			gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --log
			fail "The workflow has completed with an unsuccessful status (rc=${RC}): [${OUTCOME}]"
		fi
		;;
esac

# If everything was happy, we end up here!
quit "The workflow has completed successfully (outcome = ${OUTCOME})!"
