#!/bin/bash

set -euo pipefail
. /.functions

[ -v KUBERNETES_SERVICE_HOST ] || fail "KUBERNETES_SERVICE_HOST not defined"
[ -v KUBERNETES_SERVICE_PORT ] || fail "KUBERNETES_SERVICE_PORT not defined"
[ -v KUBERNETES_SERVICE_PORT_HTTPS ] || fail "KUBERNETES_SERVICE_PORT_HTTPS not defined"

set_or_default JENKINS_JAVA_BIN "java"

set_or_default JENKINS_JAVA_OPTS "${JAVA_OPTS:-}"

VARS=(
	-direct:JENKINS_DIRECT_CONNECTION
	-instanceIdentity:JENKINS_INSTANCE_IDENTITY
	-name:JENKINS_AGENT_NAME
	-protocols:JENKINS_PROTOCOLS
	-secret:JENKINS_SECRET
	-tunnel:JENKINS_TUNNEL
	-url:JENKINS_URL
)

CMD=()
for VAR in "${VARS[@]}" ; do
	[[ "${VAR}" =~ ^(-[^:]+):([a-zA-Z0-9_]+)(=(.*))?$ ]] || continue
	ARG="${BASH_REMATCH[1]}"
	ENV="${BASH_REMATCH[2]}"
	DEF="${BASH_REMATCH[4]}"

	set_or_default "${ENV}" "${DEF}"
	[ -n "${!ENV}" ] && CMD+=("${ARG}" "${!ENV}")
done

set_as_boolean JENKINS_WEB_SOCKET
as_boolean "${JENKINS_WEB_SOCKET}" && CMD+=(-webSocket)

set_as_default JENKINS_AGENT_WORKDIR "${HOME}"
CMD+=(-workDir "${JENKINS_AGENT_WORKDIR}")

ensure_dir "${JENKINS_AGENT_WORKDIR}"
/usr/bin/sudo /usr/bin/chown -R "$(id -u):$(id -g)" "${JENKINS_AGENT_WORKDIR}" || fail "Failed to take ownership of the work directory at [${JENKINS_AGENT_WORKDIR}]"
/usr/bin/chmod -R ug=rwX,o= "${JENKINS_AGENT_WORKDIR}" || fail "Failed to set the permissions for the work directory at [${JENKINS_AGENT_WORKDIR}]"

AGENT_DIR="${JENKINS_AGENT_WORKDIR}"
[ -n "${JENKINS_AGENT_WORKDIR}" ] || AGENT_DIR="$(mktemp -d)"

AGENT_JAR="${AGENT_DIR}/agent.jar"

download-agent "${JENKINS_URL}" "${AGENT_JAR}" || exit ${?}

set -- "${JENKINS_JAVA_BIN}" ${JENKINS_JAVA_OPTS} -jar "${AGENT_JAR}" "${CMD[@]}"

set_as_boolean JENKINS_AGENT_TEST
if as_boolean "${JENKINS_AGENT_TEST}" ; then
	JENKINS_AGENT_TEST="true"
	warn "Test mode active - old command: [${@@Q}]"
	set -- "/usr/bin/tail" "-f" "/dev/null"
fi

running "Executing the command: ${@@Q}"
exec /configure "${@}"
