#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

FUNCTIONS="${BASEDIR}/.functions"
if ! . "${FUNCTIONS}" ; then
	echo -e "ERROR: Failed to load the base functions from [${FUNCTIONS}]"
	exit 1
fi
unset FUNCTIONS

usage()
{
	echo -e "usage: ${BASH_ARGV0} git-url [regex]"
	exit 1
}

[ ${#} -lt 1 ] && usage
[ ${#} -gt 2 ] && usage

filter() {
	local REGEX="${1}"
	if [ -z "${REGEX}" ] ; then
		cat
	else
		egrep "${REGEX}"
	fi
}

git ls-remote --exit-code --symref "${1}" | \
	tail -n +2 | \
	grep '[[:space:]]refs/' | \
	grep -v '\^{}$' | \
	awk '{ print $2 }' | \
	filter "${2}"
