#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [hostname]" 1>&2
	exit 1
}

[ ${#} -le 1 ] || usage

HOST=()
if [ ${#} -eq 1 ] ; then
	HOST="${1}"
	[ -n "${HOST}" ] || fail "The hostname may not be the empty string"
	say "👉 Running Docker login for ${HOST}..."
	HOST=("${HOST}")
else
	say "👉 Running Docker login..."
fi

[ -v DOCKER_USERNAME ] || fail "The DOCKER_USERNAME environment variable is not set"

# If the password isn't on the environment, pull it from STDIN
if [ -v DOCKER_PASSWORD ] ; then
	say "👉 Logging in with Docker credentials from the environment"
else
	say "👉 Logging in with Docker credentials from STDIN..."
	DOCKER_PASSWORD="$(cat)"
fi

docker login --username "${DOCKER_USERNAME}" --password-stdin "${HOST[@]}" <<< "${DOCKER_PASSWORD}" || fail "Docker login failed (rc = ${?})"
say "\t✅ Docker login succeeded!"
exit 0
