#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

[ -v AWS_USERNAME ] || AWS_USERNAME="AWS"

[ -v AWS_REGION ] || AWS_REGION=""
[ -n "${AWS_REGION}" ] || AWS_REGION="us-east-1"
[[ "${AWS_REGION}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?$ ]] || fail "The region [${AWS_REGION}] is invalid"
export AWS_REGION

say "👉 Using region ${AWS_REGION}"
say "👉 Logging in with credentials from the environment"

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>&1) || fail "Failed to get the account ID (rc = ${?}): ${AWS_ACCOUNT_ID}"
[[ "${AWS_ACCOUNT_ID}" =~ ^[0-9]+$ ]] || fail "The account ID [${AWS_ACCOUNT_ID}] is invalid - must be a number!"
say "\t✅ Account ID identified!"

HOST="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

say "👉 Fetching the AWS login password for Docker (account ID ${AWS_ACCOUNT_ID})..."
PASS="$(aws ecr get-login-password --region "${AWS_REGION}" 2>&1)" || fail "Failed to fetch the AWS login password for account ${AWS_ACCOUNT_ID} (rc = ${?}): ${PASS}"
say "\t✅ Docker password retrieved!"

# Launch the docker login
export DOCKER_USERNAME="${AWS_USERNAME}"
exec "${BASEDIR}/login-docker" "${HOST}" <<< "${PASS}"
