#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

set_as_boolean DISABLE_DEPLOY

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} scope-1 [ scope-2 scope-3 ... scope-N ]"
	exit 1
}

[ ${#} -lt 1 ] && usage

SCOPES=""
REGEX="^@[a-z0-9~][-a-z0-9_.~]*$"
readarray -t SCOPES < <(
	for SCOPE in "${@}" ; do
		[[ "${SCOPE}" =~ ${REGEX} ]] || fail "Invalid scope format: [${SCOPE}] - must match /${REGEX}/"
		echo "${SCOPE}"
	done | sort -u
)

set_or_default NPM_PUBLISH_URL
[ -z "${NPM_PUBLISH_URL}" ] && quit "The NPM_PUBLISH_URL variable is empty, cannot configure NodeJS deployment"
[[ "${NPM_PUBLISH_URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] || fail "The NPM_PUBLISH_URL value [${NPM_PUBLISH_URL}] is not a valid URL"

(
	for P in URL TOKEN USERNAME PASSWORD ; do
		V="NPM_PUBLISH_${P}"
		[ -v "${V}" ] || continue
		declare -xg "NPM_AUTH_PUBLISH_${P}=${!V}"
	done

	export NPM_AUTH_PUBLISH_SCOPES="${SCOPES[*]}"

	exec npm-auth-configure
) || fail "Failed to configure authentication for the scopes [${SCOPES[@]}] at [${NPM_PUBLISH_URL}]!"
ok "Publishing authentication is configured!"
