#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

set_as_boolean DISABLE_DEPLOY

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} scope"
	exit 1
}

[ ${#} -ne 1 ] && usage

SCOPE="${1}"
[[ "${SCOPE}" =~ ^@[^[:space:]]+$ ]] || fail "Invalid scope format: [${SCOPE}] - must match @scope-name"

set_or_default NPM_PUBLISH_URL
[ -z "${NPM_PUBLISH_URL}" ] && quit "The NPM_PUBLISH_URL variable is empty, cannot configure NodeJS deployment"
[[ "${NPM_PUBLISH_URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] || fail "The NPM_PUBLISH_URL value [${NPM_PUBLISH_URL}] is not a valid URL"

(
	for P in URL TOKEN USERNAME PASSWORD ; do
		V="NPM_PUBLISH_${P}"
		[ -v "${V}" ] || continue
		declare -xg "NPM_AUTH_PUBLISH_${P}=${!V}"
	done

	exec npm-auth-configure
) || fail "Failed to configure authentication for the scope [${SCOPE}] at [${NPM_PUBLISH_URL}]!"

npm-config set "${SCOPE}:registry=${NPM_PUBLISH_URL}"
ok "Associated the scope [${SCOPE}] with the URL [${NPM_PUBLISH_URL}]!"
