#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

list_credentials()
{
	# Iterate over all variables that start with NPM_AUTH_
	local NAME=""
	local URL=""
	local TOKEN=""
	local USERNAME=""
	local PASSWORD=""
	local TOKEN_VALUE=""
	for VAR in "${!NPM_AUTH_@}" ; do
		[[ "${VAR}" =~ ^NPM_AUTH_(.+)_(URL|TOKEN|USERNAME|PASSWORD)$ ]] || continue
		NAME="${BASH_REMATCH[1]}"

		# First: the URL ...
		URL="NPM_AUTH_${NAME}_URL"
		[ -v "${URL}" ] || continue
		[ -z "${!URL}" ] && err "The URL for the '${NAME}' NPM repository (${URL}) is empty, it will be ignored" 1>&2 && continue
		if [[ ! "${!URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] ; then
			err "The URL [${!URL}] for the '${NAME}' NPM repository is not valid, it will be ignored" 1>&2
			continue
		fi

		TOKEN="NPM_AUTH_${NAME}_TOKEN"
		USERNAME="NPM_AUTH_${NAME}_USERNAME"
		PASSWORD="NPM_AUTH_${NAME}_PASSWORD"
		if [ -v "${TOKEN}" ] ; then
			[ -z "${!TOKEN}" ] && err "The credentials for the '${NAME}' NPM repository (${TOKEN}) are empty, it will be ignored" 1>&2 && continue
			TOKEN_VALUE="${!TOKEN}"
		else
			[ -v "${USERNAME}" ] || continue
			[ -z "${!USERNAME}" ] && continue
			[ -v "${PASSWORD}" ] || continue
			[ -z "${!PASSWORD}" ] && err "The credentials for the '${NAME}' NPM repository are incomplete - the value for ${PASSWORD} is empty" 1>&2 && continue
			TOKEN_VALUE="$(echo -n "${!USERNAME}:${!PASSWORD}" | base64 -w 0)"
		fi

		echo "${NAME} $(echo -n "${!URL}" | base64 -w 0) ${TOKEN_VALUE}"
	done | sort -u
}

COUNT=0
while read NAME URL TOKEN ; do
	# Remove the scheme
	URL="$(echo -n "${URL}" | base64 -d)"
	[[ "${URL}" =~ ^https?:(//.*) ]] && PREFIX="${BASH_REMATCH[1]}" || PREFIX="${URL}"
	# Add a final slash, if necessary
	[[ "${PREFIX}" =~ /$ ]] || PREFIX+="/"

	npm-config set "${PREFIX}:_auth=${TOKEN}"
	ok "Authentication set for the ${NAME} repository at ${URL}"
	(( ++COUNT ))
done < <(list_credentials)
ok "Found ${COUNT} repositories to configure"
