#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

generate_token()
{
	local NAME="${1}"
	local USERNAME="${2}"
	local PASSWORD="${3}"
	[ -v "${USERNAME}" ] || return 0
	[ -n "${!USERNAME}" ] || return 0
	[ -v "${PASSWORD}" ] || return 1
	[ -n "${!PASSWORD}" ] || return 1
	echo -n "${!USERNAME}:${!PASSWORD}" | base64 -w 0
}

list_credentials()
{
	# Iterate over all variables that start with NPM_AUTH_
	local NAME=""
	local URL=""
	local TOKEN=""
	local USERNAME=""
	local PASSWORD=""
	local TOKEN_VALUE=""
	for VAR in "${!NPM_AUTH_@}" ; do
		[[ "${VAR}" =~ ^NPM_AUTH_(.+)_(URL|SCOPES)$ ]] || continue
		NAME="${BASH_REMATCH[1]}"

		# First: the URL ...
		URL="NPM_AUTH_${NAME}_URL"
		[ -v "${URL}" ] || continue
		[ -z "${!URL}" ] && err "The URL for the '${NAME}' NPM registry (${URL}) is empty, it will be ignored" 1>&2 && continue
		if [[ ! "${!URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] ; then
			err "The URL [${!URL}] for the '${NAME}' NPM registry is not valid, it will be ignored" 1>&2
			continue
		fi

		TOKEN="NPM_AUTH_${NAME}_TOKEN"
		USERNAME="NPM_AUTH_${NAME}_USERNAME"
		PASSWORD="NPM_AUTH_${NAME}_PASSWORD"
		SCOPES="NPM_AUTH_${NAME}_SCOPES"
		if [ -v "${TOKEN}" ] ; then
			if [ -z "${!TOKEN}" ] ; then
				err "The credentials for the '${NAME}' NPM registry (${TOKEN}) are empty, it will be ignored" 1>&2
			else
				TOKEN_VALUE="${!TOKEN}"
			fi
		else
			TOKEN_VALUE="$(generate_token "${NAME}" "${USERNAME}" "${PASSWORD}")" || \
				err "The credentials for the '${NAME}' NPM registry are incomplete - a username was given but the value for ${PASSWORD} is empty" 1>&2
		fi

		local SCOPE_LIST=""
		if [ -v "${SCOPES}" ] ; then
			# SCOPES is a string with the scope names covered by this registry,
			# separated by commas and/or spaces
			local SCOPE_ARR=()
			readarray -t SCOPE_ARR < <(echo "${!SCOPES}" | tr '[,[:space:]]' '\n' | sed -e '/^\s*$/d' | sort -u)
			for S in "${SCOPE_ARR[@]}" ; do
				if [[ "${S}" =~ ^@[a-z0-9~][-a-z0-9_.~]*$ ]] ; then
					[ -n "${SCOPE_LIST}" ] && SCOPE_LIST+=","
					SCOPE_LIST+="${S}"
				else
					err "The scope [${S}] for the '${NAME}' NPM registry is invalid - it will be ignored (${SCOPES})" 1>&2
				fi
			done
		fi

		echo "${NAME} $(echo -n "${!URL}" | base64 -w 0) ${TOKEN_VALUE:-x} ${SCOPE_LIST}"
	done | sort -u
}

COUNT=0
while read NAME URL TOKEN SCOPES ; do
	[ -z "${SCOPES}" ] && [ "${TOKEN}" == "x" ] && warn "Neither authentication nor scopes defined for the ${NAME} registry - skipping it!" && continue
	[ "${TOKEN}" == "x" ] && TOKEN=""
	[ -n "${TOKEN}" ] && AUTH="present" || AUTH="none"
	doing "Configuring NPM for the ${NAME} registry at ${URL} (auth: ${AUTH}, scopes: ${SCOPES:-"none"}) ..."

	# Remove the scheme
	URL="$(echo -n "${URL}" | base64 -d)"
	[[ "${URL}" =~ ^https?:(//.*) ]] && PREFIX="${BASH_REMATCH[1]}" || PREFIX="${URL}"
	# Add a final slash, if necessary
	[[ "${PREFIX}" =~ /$ ]] || PREFIX+="/"

	for SCOPE in ${SCOPES//,/ } ; do
		npm-config set "${SCOPE}:registry=${URL}"
		ok "Associated the scope [${SCOPE}] with the ${NAME} registry!"
	done

	[ -n "${TOKEN}" ] || continue
	npm-config set "${PREFIX}:_auth=${TOKEN}"
	ok "Authentication set for the ${NAME} registry at ${URL}"
	(( ++COUNT ))
done < <(list_credentials)
ok "Found ${COUNT} registries to configure"
