#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

auth_params()
{
	local USER="${1}"
	local PASS=""

	if [ ${#} -eq 1 ] ; then
		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
		USER="${BASH_REMATCH[1]}"
		PASS="${BASH_REMATCH[3]}"
	else
		PASS="${2}"
	fi

	cat <<-EOF
	user "${USER}:${PASS}"
	EOF
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name"
	exit 1
}

[ ${#} -eq 1 ] || usage

#
# Make sure we're given a solid token
#
[ -v RANCHER_TOKEN ] || RANCHER_TOKEN=""
[ -n "${RANCHER_TOKEN}" ] || fail "Must provide a non-empty RANCHER_TOKEN value"
[[ "${RANCHER_TOKEN}" =~ ^[a-zA-Z0-9_-]+:.+$ ]] || fail "The RANCHER_TOKEN format is invalid"

#
# Allow for a configurable API endpoint, just in case...
#
[ -v RANCHER_API_URL ] || RANCHER_API_URL=""
[ -n "${RANCHER_API_URL}" ] || RANCHER_API_URL="https://rancher.armedia.com"

# Remove trailing slashes from the URL
[[ "${RANCHER_API_URL}" =~ ^(.*)/*$ ]] || fail "Invalid Rancher API URL [${RANCHER_API_URL}]"
RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v1/management.cattle.io.projects"

CLUSTER_NAME="${1}"
[ -n "${CLUSTER_NAME}" ] || fail "Must provide a non-empty cluster name"

CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
RANCHER_API_ENDPOINT+="/${CLUSTER_ID}"
LIST="$(curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r ".data[] | .id + \" \" + .spec.displayName")" || fail "Could not find the project listing in cluster ${CLUSTER_NAME}"
echo "${LIST}" | sort -k 2
exit 0
