#!/bin/bash
SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name [target-file]"
	exit 1
}

[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage

#
# Make sure we're given a solid token
#
[ -v RANCHER_TOKEN ] || RANCHER_TOKEN=""
[ -n "${RANCHER_TOKEN}" ] || fail "Must provide a non-empty RANCHER_TOKEN value"
[[ "${RANCHER_TOKEN}" =~ ^[a-zA-Z0-9_-]+:.+$ ]] || fail "The RANCHER_TOKEN format is invalid"

#
# Allow for a configurable API endpoint, just in case...
#
[ -v RANCHER_API_URL ] || RANCHER_API_URL=""
[ -n "${RANCHER_API_URL}" ] || RANCHER_API_URL="https://rancher.armedia.com"

# Remove trailing slashes from the URL
[[ "${RANCHER_API_URL}" =~ ^(.*)/*$ ]] || fail "Invalid Rancher API URL [${RANCHER_API_URL}]"
RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v3/clusters"

CLUSTER_NAME="${1}"
[ -n "${CLUSTER_NAME}" ] || fail "Must provide a non-empty cluster name"

#
# Allow for a target file to be specified. If not, spit out to STDOUT
#
TARGET_FILE="-"
if [ ${#} -gt 1 ] ; then
	TARGET_FILE="${2}"
	[ -n "${TARGET_FILE}" ] || fail "Must provide a non-empty target filename"
fi

CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"

CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
CLUSTER_CONFIG="$("${CURL}" -fsSL -X POST -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}/${CLUSTER_ID}?action=generateKubeconfig" | jq -r ".config")" || fail "Failed to retrieve the cluster configuration for cluster [${CLUSTER_NAME}](${CLUSTER_ID})"

#
# Write to STDOUT
#
case "${TARGET_FILE}" in
	- ) echo "${CLUSTER_CONFIG}" ; exit ${?} ;;
esac

#
# Write to the output file
#
echo -n "${CLUSTER_CONFIG}" > "${TARGET_FILE}"

# For security...
chmod 0600 "${TARGET_FILE}"

exit ${?}
