#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

auth_params()
{
	local USER="${1}"
	local PASS=""

	if [ ${#} -eq 1 ] ; then
		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
		USER="${BASH_REMATCH[1]}"
		PASS="${BASH_REMATCH[3]}"
	else
		PASS="${2}"
	fi

	cat <<-EOF
	user "${USER}:${PASS}"
	EOF
}

ADD_DESC="false"
if [ ${#} -gt 0 ] ; then
	case "${1,,}" in
		-d ) ADD_DESC="true" ;;
	esac
fi

#
# Make sure we're given a solid token
#
[ -v RANCHER_TOKEN ] || RANCHER_TOKEN=""
[ -n "${RANCHER_TOKEN}" ] || fail "Must provide a non-empty RANCHER_TOKEN value"
[[ "${RANCHER_TOKEN}" =~ ^[a-zA-Z0-9_-]+:.+$ ]] || fail "The RANCHER_TOKEN format is invalid"

#
# Allow for a configurable API endpoint, just in case...
#
[ -v RANCHER_API_ENDPOINT ] || RANCHER_API_ENDPOINT=""
[ -n "${RANCHER_API_ENDPOINT}" ] || RANCHER_API_ENDPOINT="https://rancher.armedia.com/v3/clusters"

QUERY=".data[] | .name"
"${ADD_DESC}" && QUERY+=' + " " + .description'

curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r "${QUERY}" | sort
