#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail
. /.functions

ensure_namespace_exists()
{
	local NAMESPACE="${1}"
	kubectl get namespace "${NAMESPACE}" &>/dev/null && return 0
	kubectl create namespace "${NAMESPACE}" && return 0
	return 1
}

usage()
{
	echo -e "usage: ${BASH_SOURCE:-${0}} namespace cluster-name project-name" 1>&2
	exit 1
}

[ ${#} -eq 3 ] || usage

NAMESPACE="${1}"
is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"

CLUSTER_NAME="${2}"
is_valid_hostname_part "${CLUSTER_NAME}" || fail "Invalid cluster name [${CLUSTER_NAME}]"

PROJECT_NAME="${3}"
[ -n "${PROJECT_NAME}" ] || fail "Invalid project name [${PROJECT_NAME}]"

ensure_namespace_exists "${NAMESPACE}" || fail "Failed to ensure that the required namespace ${NAMESPACE} exists"
exec "${BASEDIR}/rancher-add-ns-to-project" "${NAMESPACE}" "${CLUSTER_NAME}" "${PROJECT_NAME}"
