#!/bin/bash
RC=0
OUT="$("${@}" 2>&1)" || RC=${?}
[ ${RC} -ne 0 ] || exit 0

echo "Command failed (rc=${RC}): ${@@Q}"
if [ -n "${OUT}" ] ; then
	echo "----- BEGIN OUTPUT -----"
	echo "${OUT}"
	echo "------ END OUTPUT ------"
fi
exit ${RC}
