#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail
. /.functions

set_as_boolean DISABLE_DEPLOY

usage()
{
	echo -e "usage: ${BASH_ARGV0} scope"
	exit 1
}

[ ${#} -ne 1 ] && usage

SCOPE="${1}"
[[ "${SCOPE}" =~ ^@[^[:space:]]+$ ]] || fail "Invalid scope format: [${SCOPE}] - must match @scope-name"

as_boolean "${DISABLE_DEPLOY}" && quit "Deployment is disabled - skipping scope [${SCOPE}] to ${NPM_PUBLISH_URL}!"

stow-nodejs-configure "${SCOPE}" || exit ${?}

set_or_default LERNA_FILE "lerna.json"
if is_file_readable "${LERNA_FILE}" ; then
	say "No lerna configuration found at [${LERNA_FILE}], cannot deploy"
	exit 0
fi

#
# Temporary fix to get lerna working again
#
__NODE_MODULES="${WORKSPACE}/node_modules"
if [ -d "${__NODE_MODULES}" ] ; then
	export PATH="${__NODE_MODULES}/.bin:${PATH}"
	export NODE_PATH="${__NODE_MODULES}:${NODE_PATH}"
fi
unset __NODE_MODULES

# Pre-release? Maybe check for NPM_PUBLISH_PRERELEASE to be a non-blank
# and use that as the --preid value and switch to prerelease?
set_or_default NPM_PUBLISH_PRERELEASE
# TODO: Sanity-check this command!
[ -n "${NPM_PUBLISH_PRERELEASE}" ] && execute lerna publish prerelease --preid "${NPM_PUBLISH_PRERELEASE}" --yes --scope="${SCOPE}"

# Not a pre-release, so just deploy
execute lerna exec -- "npm publish --scope=${SCOPE}"
