#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail

[ -v UNDEPLOY_TIMEOUT ] || UNDEPLOY_TIMEOUT=""
[ -n "${UNDEPLOY_TIMEOUT}" ] || UNDEPLOY_TIMEOUT="20m"

[ -v DISABLE_UNDEPLOY ] || DISABLE_UNDEPLOY=""
case "${DISABLE_UNDEPLOY,,}" in
	true | t | yes | y ) DISABLE_UNDEPLOY="true" ;;
	* ) DISABLE_UNDEPLOY="false" ;;
esac
export DISABLE_UNDEPLOY

[ -v DISABLE_DOWNSCALE ] || DISABLE_DOWNSCALE=""
case "${DISABLE_DOWNSCALE,,}" in
	true | t | yes | y ) DISABLE_DOWNSCALE="true" ;;
	* ) DISABLE_DOWNSCALE="false" ;;
esac
export DISABLE_DOWNSCALE

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

should_uninstall()
{
	local NAMESPACE="${1}"
	local RELEASE="${2}"

	local STATUS=""

	# Have to split this or our logic won't work
	STATUS="$(helm status "${RELEASE}" --namespace "${NAMESPACE}" -o json)" || return ${?}

	# Can be one of: unknown, deployed, uninstalled,
	# superseded, failed, uninstalling, pending-install,
	# pending-upgrade or pending-rollback
	local RESULT="$(jq -r '.info.status' <<< "${STATUS}")"
	case "${RESULT,,}" in
		uninstalled ) return 1 ;;
		* ) return 0 ;;
	esac
}

is_valid_name()
{
	local STR="${1}"
	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
	return 0
}

execute()
{
	#
	# Show the command about to be executed
	#
	say "${@@Q}"
	if "${DISABLE_UNDEPLOY}" ; then
		warn "Undeployment disabled: skipping the command execution"
		return 0
	fi

	#
	# Proceed with the execution
	#
	( exec "${@}" )
	return ${?}
}

is_namespace_exists()
{
	local NAMESPACE="${1}"
	execute kubectl get namespace "${NAMESPACE}" &>/dev/null || return ${?}
	return 0
}

wait_for_pods_to_die()
{
	local ELEMENT="${1}"

	local JSON=""
	JSON="$(kubectl get "${ELEMENT}" -o json)" || return ${?}

	local JQ_EXPR='.spec.selector.matchLabels | keys[] as $k | "\($k)=\(.[$k])"'
	local LABELS=""
	LABELS="$(jq -r "${JQ_EXPR}" <<< "${JSON}" | tr '\n' ',' | sed -e 's;,$;;g')" || return ${?}
	[ -n "${LABELS}" ] || return 1

	# Wait for up to 5 minutes
	execute kubectl wait --for=delete pods -l "${LABELS}" --timeout 5m
}

usage()
{
	echo -e "usage: ${BASH_SOURCE:-${0}} [namespace] release" 1>&2
	exit 1
}

[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage

if [ ${#} -eq 1 ] ; then
	NAMESPACE="$(kubectl config view --minify -o jsonpath="{..namespace}")"
	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
else
	NAMESPACE="${1}"
	shift
fi
is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"

RELEASE="${1}"
is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"

# If the target namespace doesn't exist, by extension the environment doesn't exist
if ! is_namespace_exists "${NAMESPACE}" ; then
	say "The namespace ${NAMESPACE} does not exist, so nothing to remove"
	exit 0
fi

if ! should_uninstall "${NAMESPACE}" "${RELEASE}" ; then
	say "The Helm deployment ${RELEASE} was not found in the ${NAMESPACE} namespace"
	exit 0
fi

if ! "${DISABLE_DOWNSCALE}" ; then
	#
	# Before we uninstall, we will scale down all Deployments and StatefulSets to 0
	# replicas, in hopes that this will help things along in terms of volume assignment
	# and whatnot
	#
	warn "Downscaling pod controller elements prior to uninstallation"
	readarray -t ELEMENTS < <(kubectl get statefulset -o name && kubectl get deployment -o name)
	if [ "${#ELEMENTS[@]}" -gt 0 ] ; then
		if execute kubectl scale "${ELEMENTS[@]}" --replicas 0 ; then
			# Wait for all popds related to the given elements to disappear ...
			for E in "${ELEMENTS[@]}" ; do
				wait_for_pods_to_die "${E}" || warn "Failed to wait for the pods to disappear for ${E}"
			done
		else
			warn "Failed to scale down the pod controller elements"
		fi
	fi
fi

# Delete the old installation, since it's the safest bet to ensure
# that the correct resources, containers, and deployments are used
execute \
	helm uninstall "${RELEASE}" \
		--namespace "${NAMESPACE}" \
		--keep-history \
		--cascade foreground \
		--wait \
		--timeout "${UNDEPLOY_TIMEOUT}" || \
	fail "The Helm undeployment has failed, please review the logs"

# All is well... exit!
exit 0
