#!/bin/bash
set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appId" 1>&2
	exit 1
}

[ ${#} -eq 1 ] || usage

# Get from parameters
APP_ID="${1}"
[ -n "${APP_ID}" ] || fail "The application ID may not be the empty string"

[ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
[ -v VERACODE_API_KEY_SECRET ] || fail "The VERACODE_API_KEY_SECRET variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_SECRET}" ] || fail "The VERACODE_API_KEY_SECRET variable has an empty value, cannot continue"

XML="$(veracode -action getapplist)" || fail "Failed to retrieve the application list"

# Find the application with the correct (case-sensitive) name, and spit
# out the Application ID

APP_NAME="$(echo -n "${XML}" | xmlstarlet sel -N "al=https://analysiscenter.veracode.com/schema/2.0/applist" -t -v "/al:applist/al:app[@app_id='${APP_ID}']/@app_name")" || fail "Failed to get the Application name for [${APP_ID}]"
echo "${APP_NAME}"
