#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appName" 1>&2
	exit 1
}

[ ${#} -eq 1 ] || usage

# Get from parameters
APP_NAME="${1}"
[ -n "${APP_NAME}" ] || fail "The application name may not be the empty string"

[ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
[ -v VERACODE_API_KEY_SECRET ] || fail "The VERACODE_API_KEY_SECRET variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_SECRET}" ] || fail "The VERACODE_API_KEY_SECRET variable has an empty value, cannot continue"

XML="$(veracode -action getapplist)" || fail "Failed to retrieve the application list"

# Find the application with the correct (case-sensitive) name, and spit
# out the Application ID

APP_ID="$(xmlstarlet sel -N "al=https://analysiscenter.veracode.com/schema/2.0/applist" -t -v "/al:applist/al:app[@app_name='${APP_NAME}']/@app_id" <<< "${XML}")" || exit ${?}
echo "${APP_ID}"
exit 0
