#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appId buildId" 1>&2
	exit 1
}

[ ${#} -eq 2 ] || usage

# Get from parameters
APP_NAME="${1}"
[ -n "${APP_NAME}" ] || fail "The application name may not be the empty string"

BUILD_ID="${2}"
[ -n "${BUILD_ID}" ] || fail "The build id may not be the empty string"

[ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
[ -v VERACODE_API_KEY_SECRET ] || fail "The VERACODE_API_KEY_SECRET variable is not set, cannot continue"
[ -n "${VERACODE_API_KEY_SECRET}" ] || fail "The VERACODE_API_KEY_SECRET variable has an empty value, cannot continue"

# Compute the application ID based on the name
APP_ID="$("${BASEDIR}/veracode-get-app-id" "${APP_NAME}")" || fail "Failed to get the application ID for [${APP_NAME}]"

BUILDINFO="$(veracode -action GetBuildInfo -appid "${APP_ID}" -buildid "${BUILD_ID}" -format xml)" || fail "Failed to fetch the build information!"

STATUS="$(xmlstarlet sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/bi:analysis_unit/@status" <<< "${BUILDINFO}")" || fail "Failed to get the build status for Application [${APP_NAME}], build [${BUILD_ID}]"

echo "${STATUS}"
exit 0
